name: Delivery App Deployment

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Add this on to Repository secrates
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Add this on to Repository secrates
          aws-region: ap-south-1  # Change this to your AWS region

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync . s3://shop-for-eating --delete
